name: gen_pod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - numpy
  - pydub
  - plotly
  - streamlit
  - pip:
      - openai>=1.0.0
      - pyannote.audio
      - huggingface_hub
      - torch
      - torchaudio
      - torchvision